// <auto-generated />
using ClothesStoreApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothesStoreApp.Migrations
{
    [DbContext(typeof(ClStoreContext))]
    partial class ClStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothesStoreApp.Articole", b =>
                {
                    b.Property<int>("ArticolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticolId"));

                    b.Property<string>("ArticolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticolType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ArticoleCost")
                        .HasColumnType("float");

                    b.HasKey("ArticolId");

                    b.ToTable("Clothes");
                });
#pragma warning restore 612, 618
        }
    }
}
